apiVersion : apps/v1
kind: Deployment
metadata:
  name: sanjaydahiyaazuredevopsclass 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sanjaydahiyaazuredevopsclass
  template:
    metadata:
      labels:
        app: sanjaydahiyaazuredevopsclass 
    spec:
      containers:
        - name: sanjaydahiyaazuredevopsclass 
          image: devopsacrprject.azurecr.io/sanjaydahiyaazuredevopsclass
          ports:
          - containerPort: 80